### ISSUE TITLE
PayPal IPN 

### ISSUE THREAD

**Issue by rpamfil** [JMAConsulting/biz.jmaconsulting.grantapplications#111]
We have an event page that takes payments that are then confirmed by PayPal via IPN.
When the IPN comes back, somehow the grant applications extension gets involved while it is loading the profile for the event registration. This leads to a fatal error, and the email confirmation for the payment is never sent by Civi.

```
Jul 06 20:39:05  [info] Contribution record updated successfully

Jul 06 20:39:05  [info] $Fatal Error Details = Array
(
    [message] => The requested Profile (gid=17) is disabled OR it is not configured to be used for 'Profile' listings in its Settings OR there is no Profile with that ID OR you do not have permission to access this profile. Please contact the site administrator if you need assistance.
    [code] =>
)


Jul 06 20:39:05  [info] $backTrace = #0 /data/www/example.org/wp/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(363): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /data/www/example.org/wp/wp-content/plugins/civicrm/custom_ext/biz.jmaconsulting.grantapplications-1.4.1/CRM/Core/BAO/UFGroup.php(356): CRM_Core_Error::fatal("The requested Profile (gid=17) is disabled OR it is not configured to be used...")
#2 /data/www/example.org/wp/wp-content/plugins/civicrm/civicrm/CRM/Event/BAO/Event.php(1304): CRM_Core_BAO_UFGroup::getFields("17", FALSE, 4, NULL, NULL, FALSE, NULL, FALSE, NULL, 4, "field_name", TRUE)
#3 /data/www/example.org/wp/wp-content/plugins/civicrm/civicrm/CRM/Event/BAO/Event.php(1146): CRM_Event_BAO_Event::buildCustomDisplay("17", "customPre", "15176", Object(CRM_Core_Smarty), "4831", NULL, NULL, (Array:0))
#4 /data/www/example.org/wp/wp-content/plugins/civicrm/civicrm/CRM/Contribute/BAO/Contribution.php(2221): CRM_Event_BAO_Event::sendMail("15176", (Array:9), "4831", NULL, FALSE)
#5 /data/www/example.org/wp/wp-content/plugins/civicrm/civicrm/CRM/Core/Payment/BaseIPN.php(853): CRM_Contribute_BAO_Contribution->composeMessageArray((Array:31), (Array:6), (Array:9), FALSE, FALSE)
#6 /data/www/example.org/wp/wp-content/plugins/civicrm/civicrm/CRM/Core/Payment/BaseIPN.php(788): CRM_Core_Payment_BaseIPN->sendMail((Array:31), (Array:6), (Array:8), (Array:9), FALSE, FALSE)
#7 /data/www/example.org/wp/wp-content/plugins/civicrm/civicrm/CRM/Core/Payment/PayPalIPN.php(290): CRM_Core_Payment_BaseIPN->completeTransaction((Array:31), (Array:6), (Array:8), Object(CRM_Core_Transaction), FALSE)
#8 /data/www/example.org/wp/wp-content/plugins/civicrm/civicrm/CRM/Core/Payment/PayPalIPN.php(347): CRM_Core_Payment_PayPalIPN->single((Array:31), (Array:6), (Array:8), FALSE, FALSE)
#9 /data/www/example.org/wp/wp-content/plugins/civicrm/civicrm/extern/ipn.php(52): CRM_Core_Payment_PayPalIPN->main()
#10 {main}
```

Looking at the code in the referenced UFGroup.php at line 325, it looks like $skipPermission should be set to avoid checks during registration or when using profiles for anonymous users, but that is not implemented in the function.
```
    // add permissioning for profiles only if not registration
    if (!$skipPermission) {
```

**Comment by JoeMurray** [comment]
The extension overrides that core file. What version of CiviCRM are you using?

**Comment by rpamfil** [comment]
I'm using 4.6.4 (Wordpress).

**Comment by rpamfil** [comment]
I checked the diff between the version of UFGroup.php that your extension is supplying and the stock one, and I cannot see any difference that would explain this error. Either the bug is in the stock handling of these fields, or we have some data corruption that is causing this. Give me a few days to check and I will confirm if I can isolate this error to when your extension is on.
Thanks.

**Comment by rpamfil** [comment]
I can confirm that the error disappears when the extension is turned off. So the extension is causing the problem. I am not sure what in the UFGroup.php is causing it, but changing $skipPermission=TRUE in line 291 makes the error disappear. I can provide a full diff to make sure that the version I have has the correct relationship to the original UFGroup.php, but I can't attach it.

**Comment by JoeMurray** [comment]
Yes, please provide diff. Thanks!!

**Comment by rpamfil** [comment]
Here is the diff:
http://pastebin.com/prbKLZLc
The first section of the diff is the change to $skipPermission that I made to work around the error.

**Comment by JoeMurray** [comment]
And can you provide information on what profile 17 is used for (Event participants?), and what the fields in the profile are (eg contact core fields, contact custom fields, participant core...). Thanks.

**Comment by rpamfil** [comment]
Thanks for looking into this.
I got this error for profile 17, which is on an event form, and then for
profile 13, which is on our donation form. It seems like it doesn't matter
what the profile is.
I think the key here is that the script runs out of ipn.php. It may be that
the user or permission level available in that environment may be more
limited than if you're looking on a form in a fully bootstrapped CMS.
Is your extension overriding any other files that may be indirectly
affecting the processing an update to a contribution?

Profile 13 fields:

​Field Name
I want to remain anonymous(Contribution custom field)
First Name(Individual)
Last Name(Individual)
Street Address(Contact)
Additional Address(Contact)
ZIP/Postal Code(Contact)
City(Contact)
Country(Contact)
State(Contact)
Designation(Contribution custom field)
If NOT a member, I would like to be contacted by:(Contact custom field)

**Comment by JoeMurray** [comment]
@rpamfil Here's some feedback from Kevin Christiano. I'm going to loop him in here since this seems to be an IPN issue that may have had a fix for 4.6.4 that broke our stuff??

" There was an issue with the ipn.php for PayPal in version 4.5.   It was
OK in 4.4 and fixed in 4.6.3.

"The fix was making sure that the CMS got bootstrapped (Drupal was all
set, WP fixed in 4.6.3) and that the default action was to allow the IPN
callback to update CiviCRM."

**Comment by kcristiano** [comment]
Taking a look at this,  The problem seems to be related to the value of `$skipPermission`

In the pastebin, it shows that CRM_Core_BAO_UFGroup sets this as follows:

`$skipPermission = FALSE,`

This is correct as we need to boot WP and get the proper permissions to send the emails out to confirm the transaction.

Thisi was done here:

PayPal IPN Fix : 
WP: https://github.com/civicrm/civicrm-wordpress/pull/75
Core: https://github.com/civicrm/civicrm-core/pull/5833

In looking in the JMA code, I do see that https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/blob/4.6/CRM/Core/BAO/UFGroup.php#L289 has the value for $skipPermissions set to FALSE.

I can't test this myself right now, but the files for GrantApplication on GitHub look correct.  

@rpamfil can you verify the version of GrantApplications and compare your UF_Group.php to the 4.6 branch in GitHub.   My best guess is that this is where the problem lies.

**Comment by kcristiano** [comment]
@rpamfil 
I was able to do a test of an event payment.  Using CiviCRM 4.6.5, WP 4.2.2 and Grant Applications 4.6.

The IPN suceeded and the emails went out.

However, I did not overwite the civicrm core files as suggested in the README.md.  @JoeMurray Do you have a roadmap to use the new hooks that have been provided in https://github.com/civicrm/civicrm-wordpress/commit/411e1385a805fa89946d0e6ef979aca427a82be2 ?

**Comment by pradpnayak** [comment]
I have updated some core file that included changes for https://issues.civicrm.org/jira/browse/CRM-16776.

@rpamfil could you try replacing the extension with new code base available at https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/archive/4.6.zip

**Comment by rpamfil** [comment]
Thank you gentlemen for the help and troubleshooting here. After upgrading to 4.6.5 and downloading the latest code from @pradpnayak, I am still getting this error and stack trace (with updated line numbers after the upgrades). In the next few weeks I will be doing some more testing on this site and trying to replicate this with a clean install. I'll report back then with more information. In the meantime, you can close this issue -- it's probably just an oddity with our setup.

Regarding the replacing of files for shortcodes, I have a clarification question. The instructions below read to me as saying that you are supposed to copy from wp-content/plugins/civicrm into wp-content/plugins/civicrm/custom_ext/biz.jmaconsulting.../shortcode-wp. @kcristiano seems to imply above that you're supposed to copy FROM the extension into CRM core. Which is it?

>    a. In order to enable shortcode support for WordPress installations, please replace the civicrm modal files present under the shortcode-wp directory, with the ones that come with the default CiviCRM installation. They can be found under wp-content/plugins/civicrm in most cases.

**Comment by kcristiano** [comment]
@rpamfil The way I am reading the notes, you would need to copy the contenst of the shortcode-wp directory (two directories assets and includes) into wp-content/plugins/civicrm

This is the main civicrm plugin directory and it has the assests and includes directories.  The extensions files will overwrite the existing ones and add shortcode functionality for Grants.

@JoeMurray Please advise if I have this incorrect.

**Comment by Edzelopez** [comment]
@kcristiano Yes, that is correct.

**Comment by rpamfil** [comment]
Just in case anyone else gets this mysterious error.
I discovered that the error had to do with the permissions of the anonymous user role in Wordpress (or lack thereof). Here is a useful thread on this topic: http://civicrm.stackexchange.com/questions/2988/problem-with-online-registration-after-moving-to-new-url/6411#6411

I am not sure why, in my previous testing, the problem only manifested when the grantapplications extension was on, but after turning the extension off, it looks like the problem persisted on other event IPNs. Thereafter I continued my search and found that this had to do with permissions.
